name: Deploy JsDoc to GitHub pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install requirements
        run: npm i jsdoc-autoprivate docdash

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./larkjs
          output_dir: ./out
          config_file: jsdoc_conf.json
          template: minami
          front_page: README.md

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.